system two

two.append ZAFnvagrtot =c(1)+c(2)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)+c(3)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)+c(4)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)+c(5)*log(ZAFNVAGRSMKN) 

two.append ZAFNVENETOT=c(6)+c(4)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)+c(8)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)+c(9)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)+c(10)*log(ZAFNVENESMKN)'

two.append ZAFNVOTHRETOT=c(11)+c(3)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)+c(13)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)+c(8)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)+c(15)*log(ZAFNVINDSMKN)
smpl 2000 2019
two.fiml(rcov=diag) 
two.sur 

' OR

equation _tet.ls log(ZAFNYGDPFCSTCN/ZAFNVSRVTOTLXN) = C(1)+C(2)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)+C(3)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)+C(4)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)+c(5)*log(ZAFNYGDPFCSTKN)+0.5*c(6)*log(ZAFNYGDPFCSTKN)^2+c(7)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)+c(8)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)+c(9)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)+0.5*c(10)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)^2+0.5*C(11)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)^2+0.5*C(12)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)^2+c(13)*log(ZAFNYGDPFCSTKN)*log(ZAFnvagrtotlxn/ZAFNVSRVTOTLXN)+C(14)*log(ZAFNYGDPFCSTKN)*log(ZAFNVINDOTHRXN/ZAFNVSRVTOTLXN)+C(15)*log(ZAFNYGDPFCSTKN)*log(ZAFNVENGTOTLXN/ZAFNVSRVTOTLXN)

' Shares

' OR

system three

three.append ZAFnvagrtot =c(1)+c(2)*log(ZAFnvagrtotlxn)+c(3)*log(ZAFNVINDOTHRXN)+c(4)*log(ZAFNVENGTOTLXN)+(1-c(2)-c(3)-c(4))*log(ZAFNVSRVTOTLXN)+c(5)*log(ZAFNVAGRSMKN) 

three.append ZAFNVENETOT=c(6)+c(4)*log(ZAFnvagrtotlxn)+c(8)*log(ZAFNVINDOTHRXN)+c(9)*log(ZAFNVENGTOTLXN)+(1-c(4)-c(8)-c(9))*log(ZAFNVSRVTOTLXN)+c(10)*log(ZAFNVENESMKN)

three.append ZAFNVOTHRETOT=c(11)+c(3)*log(ZAFnvagrtotlxn)+c(13)*log(ZAFNVINDOTHRXN)+c(8)*log(ZAFNVENGTOTLXN)+(1-c(3)-c(13)-c(8))*log(ZAFNVSRVTOTLXN)+c(15)*log(ZAFNVINDSMKN)

smpl 2000 2019
three.fiml(rcov=diag) 
three.sur 

