system two

two.append BGDnvagrtot =c(1)+c(2)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)+c(3)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)+c(4)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)+c(5)*log(BGDNVAGRSMKN) 

two.append BGDNVENETOT=c(6)+c(4)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)+c(8)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)+c(9)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)+c(10)*log(BGDNVENESMKN)'

two.append BGDNVOTHRETOT=c(11)+c(3)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)+c(13)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)+c(8)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)+c(15)*log(BGDNVINDSMKN)
smpl 2000 2019
two.fiml(rcov=diag) 
two.sur 

' OR

equation _tet.ls log(BGDNYGDPFCSTCN/BGDNVSRVTOTLXN) = C(1)+C(2)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)+C(3)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)+C(4)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)+c(5)*log(BGDNYGDPFCSTKN)+0.5*c(6)*log(BGDNYGDPFCSTKN)^2+c(7)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)+c(8)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)+c(9)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)+0.5*c(10)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)^2+0.5*C(11)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)^2+0.5*C(12)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)^2+c(13)*log(BGDNYGDPFCSTKN)*log(BGDnvagrtotlxn/BGDNVSRVTOTLXN)+C(14)*log(BGDNYGDPFCSTKN)*log(BGDNVINDOTHRXN/BGDNVSRVTOTLXN)+C(15)*log(BGDNYGDPFCSTKN)*log(BGDNVENGTOTLXN/BGDNVSRVTOTLXN)

' Shares

' OR

system three

three.append BGDnvagrtot =c(1)+c(2)*log(BGDnvagrtotlxn)+c(3)*log(BGDNVINDOTHRXN)+c(4)*log(BGDNVENGTOTLXN)+(1-c(2)-c(3)-c(4))*log(BGDNVSRVTOTLXN)+c(5)*log(BGDNVAGRSMKN) 

three.append BGDNVENETOT=c(6)+c(4)*log(BGDnvagrtotlxn)+c(8)*log(BGDNVINDOTHRXN)+c(9)*log(BGDNVENGTOTLXN)+(1-c(4)-c(8)-c(9))*log(BGDNVSRVTOTLXN)+c(10)*log(BGDNVENESMKN)

three.append BGDNVOTHRETOT=c(11)+c(3)*log(BGDnvagrtotlxn)+c(13)*log(BGDNVINDOTHRXN)+c(8)*log(BGDNVENGTOTLXN)+(1-c(3)-c(13)-c(8))*log(BGDNVSRVTOTLXN)+c(15)*log(BGDNVINDSMKN)

smpl 2000 2019
three.fiml(rcov=diag) 
three.sur


